### ISSUE TITLE
A issue about the mapping file

### ISSUE THREAD

**Issue by LeoWang2007** [Escartem/AnimeWwise#6]
Hello~
Recently, I tried using this project to unpack the background music of the game(Music*.pck). It successfully unpacked it, but have no filename. 
May I ask how you get the map files? I find some file in the GenshinData project, it may be background music map file, but I don't know how to use it, so I want to ask you for help. 

Like this: 
![图片](https://github.com/Escartem/AnimeWwise/assets/79351490/02a6f8f2-0fb6-477c-b83f-19545a28edce)
![图片](https://github.com/Escartem/AnimeWwise/assets/79351490/4bc2bb4f-6bf0-47ce-9272-d10a011f8207)

**Comment by Escartem** [comment]
the map file is made by myself, it's a custom format for this projecct to store links between file hashes and original names, in order to create it I do indeed use what you showed in genshin data, and apply math and encryption to find out the original hash and store it in the file. the process is a bit long to explain here but basically it's just storing what's in genshin data in an optimised way so you can get filename instantly. also I just updated it to 4.4 so you may want to retry to see if it includes filenames now even though it is not guaranted

**Comment by LeoWang2007** [comment]
So may I know what is the meaning of  `AAOKCKCLPCI` and `OHDMNOBCMAG` I have work on it for a long time. Thank you!

**Comment by LeoWang2007** [comment]
The new version map file seems to be working properly either. Some music file I know the name (show in the upper images like `music_scene_mengde_church`) is still in unmapped folder. 

It seems like something's wrong...
![图片](https://github.com/Escartem/AnimeWwise/assets/79351490/65298cbc-06a3-45e3-9e00-bafcf29b1068)

**Comment by Escartem** [comment]
> So may I know what is the meaning of  `AAOKCKCLPCI` and `OHDMNOBCMAG` I have work on it for a long time. Thank you! 

I don't think there's a meaning for it, it's probably encrypted, before 4.4 it was called SourceNames. As for the mapping file, it's possible only voice lines files where included, where in Genshin data did you got the file you're showing ?

**Comment by LeoWang2007** [comment]
I got it at `AnimeGameData(ROOT)\BinOutput\Audio\MusicSegment`

**Comment by LeoWang2007** [comment]
I got the file in this path: `AnimeGameData(ROOT)\BinOutput\Audio\MusicSegment`

**Comment by LeoWang2007** [comment]
What are the voice `sourceName` you find? Are there directly save in the file?

**Comment by Escartem** [comment]
> Where are the voice `sourceName` you find? Are they directly save in the file?

there are in BinOutput\Voice\Items but not anymore since 4.4 it's random letters like you have

I tried to compile a mapping using the Loner.json file you mentioned, try replacing the mapping file in the tool by this one and tell me if it adds the names this time

[latest.zip (the .map is inside)](https://github.com/Escartem/AnimeWwise/files/14157023/latest.zip)

**Comment by LeoWang2007** [comment]
It doesn't work either... All files in unmapped folder.

**Comment by LeoWang2007** [comment]
Do you have some other idea?

**Comment by LeoWang2007** [comment]
I don't know if this matter will affect the outcome of unpacking? I'm using Genshin Impact Chinese version, perhaps its index is different from the international version?

**Comment by Escartem** [comment]
No the index includes all 4 languages, only explanation is that it is just not possible to map, it's because there is a name in dumped data that it is possible to link it into the game, voice lines are known to have very good coverage but the rest doesn't. So I'm assuming it's just not mappable or requires different techniques

**Comment by LeoWang2007** [comment]
I found that the uploader on YouTube have already uploaded those music, and they uploaded it very quickly, just behind official updated the game.
Like: 
https://www.youtube.com/watch?v=oLu3sh3DrFA
https://www.youtube.com/watch?v=RDzaFnjeiLg
![图片](https://github.com/Escartem/AnimeWwise/assets/79351490/e6b096be-d497-4f96-84d9-441706c58cc0)
So I think there must be a way to get the filename, and someone have found it. But I didn't find anything in GitHub

**Comment by LeoWang2007** [comment]
Here's a repo about the filename https://github.com/w4123/GenshinVoice, but last update is last year.

**Comment by Escartem** [comment]
> I found that the uploader on YouTube have already uploaded those music, and they uploaded it very quickly, just behind official updated the game. So I think there must be a way to get the filename, and someone have found it. But I didn't find anything in GitHub

Mihoyo releases albums of their music constantly, so it's pretty easy to [get the music](https://music.youtube.com/channel/UCJ4yjqc1XuGgiE35NsSSkYA)

And as for the repo you mentionned, it's for voice only and that's what i'm already doing, I don't think it covers anything else than voice lines

**Comment by LeoWang2007** [comment]
> Mihoyo releases albums of their music constantly, so it's pretty easy to [get the music](https://music.youtube.com/channel/UCJ4yjqc1XuGgiE35NsSSkYA)
But this music they haven't upload, it's the latest music in 4.4

**Comment by Escartem** [comment]
Well I don't really know to be honest, but I'm sure the music uploaded on yt is not coming from the game directly (aka extracted), there's probably something else involved. As for just music name mapping, I haven't found a workaround yet

**Comment by LeoWang2007** [comment]
OK, it's really a difficult thing to find the music name map. Thanks a lot for your work, I will also find the way. 
But getting the music so early like that, getting them from the game is the only way I can think of it. Others way, like the official version introduction or character demo all have vocals in music, they can't get the music so clear.

**Comment by Escartem** [comment]
It's been a while since this was last active, I've been working on improving mapping coverage on v2 branch since then, music is still not guaranteed though :/
will close unless otherwise specified by you
